Repository thm-mni-ii/SWT-P_SS20_Overcooked, pull requests merged in 2020-08, with the labels that each got.

#99 Individual score reward for each matter & Time limited demands
  Assets/GameData/Matter/Compounds/CompoundC2H4O2.asset
  Assets/GameData/Matter/Compounds/CompoundC2H6.asset
  Assets/GameData/Matter/Compounds/CompoundC2H6O.asset
  Assets/GameData/Matter/Compounds/CompoundC5H4N4O3.asset
  Assets/GameData/Matter/Compounds/CompoundCH4.asset
  Assets/GameData/Matter/Compounds/CompoundCH4O.asset
  Assets/GameData/Matter/Compounds/CompoundCO.asset
  Assets/GameData/Matter/Compounds/CompoundCO2.asset
  Assets/GameData/Matter/Compounds/CompoundH2O.asset
  Assets/GameData/Matter/Elements/ElementC.asset
  Assets/GameData/Matter/Elements/ElementH.asset
  Assets/GameData/Matter/Elements/ElementN.asset
  Assets/GameData/Matter/Elements/ElementO.asset
  Assets/GameData/Matter/Molecules/MoleculeH2.asset
  Assets/GameData/Matter/Molecules/MoleculeO2.asset
  Assets/Prefabs/UI/DemandedMatterUI.prefab
  Assets/Scripts/DemandQueue.cs
  Assets/Scripts/DemandedMatterUI.cs
  Assets/Scripts/Level.cs
  Assets/Scripts/ScriptableObjects/Matter/Matter.cs
Labels: bug, gameplay, improvement, networking, sprint

#101 Separate UI logic from game logic for the Level Timer and Demand Queue
  Assets/Prefabs/UI/DemandQueueUI.prefab
  Assets/Prefabs/UI/DemandQueueUI.prefab.meta
  Assets/Prefabs/UI/LevelTimerUI.prefab
  Assets/Prefabs/UI/LevelTimerUI.prefab.meta
  Assets/Prefabs/UI/LevelUI.prefab
  Assets/Scenes/Level1.unity
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Demand.cs
  Assets/Scripts/Demand.cs.meta
  Assets/Scripts/DemandQueue.cs
  Assets/Scripts/DemandQueueUI.cs
  Assets/Scripts/DemandQueueUI.cs.meta
  Assets/Scripts/DemandedMatterUI.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Level.cs
  Assets/Scripts/LevelTimer.cs
  Assets/Scripts/LevelTimer.cs.meta
  Assets/Scripts/LevelTimerUI.cs
  Assets/Scripts/LevelTimerUI.cs.meta
  Assets/Scripts/LevelUI.cs
  Assets/Scripts/TestNetworkManager.cs
  Assets/Scripts/UIManager.cs
Labels: UI, bug, urgent

#107 Highlight objects the player is looking at
  Assets/Materials/HighlightEffectMaterial.mat
  Assets/Materials/HighlightEffectMaterial.mat.meta
  Assets/Prefabs/Level/BunsenBurner.prefab
  Assets/Prefabs/Level/DistillationEquipment.prefab
  Assets/Prefabs/Level/ElectrolysisEquip.prefab
  Assets/Prefabs/Level/MatterSupplyBox.prefab
  Assets/Prefabs/Level/MethanolEquipmentSmall.prefab
  Assets/Prefabs/Level/NaCl_Experiment_Equipment.prefab
  Assets/Prefabs/Level/Tables/Drawers1x1FlatTable.prefab
  Assets/Prefabs/Level/Tables/Drawers1x1Table.prefab
  Assets/Prefabs/Level/TrashCan.prefab
  Assets/Prefabs/Level/Uricacid.prefab
  Assets/Prefabs/Level/WaterTank.prefab
  Assets/Prefabs/Level/distillationModern.prefab
  Assets/Prefabs/Level/ethanacidEquip.prefab
  Assets/Prefabs/MatterObjects/MatterObject.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Interactables/DrawersTable.cs
  Assets/Scripts/Interactables/IInteractable.cs
  Assets/Scripts/Interactables/ModifiableObject.cs
  Assets/Scripts/Interactables/PickableObject.cs
  Assets/Scripts/Interactor.cs
  Assets/Scripts/MatterSupplyBox.cs
  Assets/Scripts/ObjectHighlighting.cs
  Assets/Scripts/ObjectHighlighting.cs.meta
  Assets/Shaders/HighlightEffect.shader
  Assets/Shaders/HighlightEffect.shader.meta
Labels: feature, gameplay, visuals

#108 Block player controls when level timer expires
  Assets/Prefabs/Player.prefab
  Assets/Scripts/Level.cs
  Assets/Scripts/Player.cs
  Assets/Scripts/PlayerControls.cs
Labels: bug, gameplay

#112 split points and amount of recipes, removed placeholder
  Assets/Prefabs/UI/LevelFinishedUI.prefab
  Assets/Prefabs/UI/LevelFinishedUI.prefab.meta
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Level.cs
  Assets/Scripts/LevelFinishedUI.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: improvement, sprint

#117 Level phases
  Assets/Animations/Player.meta
  Assets/Animations/Player/PlayerNameCanvas.meta
  Assets/Animations/Player/PlayerNameCanvas/_PlayerNameCanvas.controller
  Assets/Animations/Player/PlayerNameCanvas/_PlayerNameCanvas.controller.meta
  Assets/Animations/Player/PlayerNameCanvas/hidden.anim
  Assets/Animations/Player/PlayerNameCanvas/hidden.anim.meta
  Assets/Animations/Player/PlayerNameCanvas/hide.anim
  Assets/Animations/Player/PlayerNameCanvas/hide.anim.meta
  Assets/Animations/Player/PlayerNameCanvas/init.anim
  Assets/Animations/Player/PlayerNameCanvas/init.anim.meta
  Assets/Animations/Player/PlayerNameCanvas/show.anim
  Assets/Animations/Player/PlayerNameCanvas/show.anim.meta
  Assets/Animations/Player/PlayerNameCanvas/shown.anim
  Assets/Animations/Player/PlayerNameCanvas/shown.anim.meta
  Assets/Prefabs/Player.prefab
  Assets/Scripts/Demand.cs
  Assets/Scripts/DemandQueue.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Interactor.cs
  Assets/Scripts/Level.Finished.cs
  Assets/Scripts/Level.Finished.cs.meta
  Assets/Scripts/Level.Init.cs
  Assets/Scripts/Level.Init.cs.meta
  Assets/Scripts/Level.Playing.cs
  Assets/Scripts/Level.Playing.cs.meta
  Assets/Scripts/Level.Preparing.cs
  Assets/Scripts/Level.Preparing.cs.meta
  Assets/Scripts/Level.cs
  Assets/Scripts/LevelPhase.cs
  Assets/Scripts/LevelPhase.cs.meta
  Assets/Scripts/Messages/ConnectionRequestMessage.cs
  Assets/Scripts/Messages/ConnectionRequestMessage.cs.meta
  Assets/Scripts/Player.cs
  Assets/Scripts/PlayerConnection.cs
  Assets/Scripts/PlayerControls.cs
  Assets/Scripts/PlayerInfo.cs
  Assets/Scripts/PlayerInfo.cs.meta
  Assets/Scripts/State.cs
  Assets/Scripts/State.cs.meta
  Assets/Scripts/StateMachine.cs
  Assets/Scripts/StateMachine.cs.meta
  Assets/Scripts/TestNetworkManager.cs
  Assets/Scripts/UIBillboard.cs
  Assets/Scripts/UIBillboard.cs.meta
  Assets/Scripts/UIManager.cs
  Assets/Scripts/Utils.cs
  Assets/Scripts/Utils.cs.meta
Labels: UI, bug, feature, gameplay, improvement

#122 Equipment contents UI
  Assets/Prefabs/Level/AceticAcidEquip.prefab
  Assets/Prefabs/Level/BunsenBurner.prefab
  Assets/Prefabs/Level/DistillationEquipment.prefab
  Assets/Prefabs/Level/ElectrolysisEquip.prefab
  Assets/Prefabs/Level/MethanolEquipmentSmall.prefab
  Assets/Prefabs/Level/Multitool.prefab
  Assets/Prefabs/Level/Uricacid.prefab
  Assets/Prefabs/Level/distillationModern.prefab
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/UI/ContentsUI.prefab
  Assets/Prefabs/UI/ContentsUI.prefab.meta
  Assets/Prefabs/UI/MatterIcon.prefab
  Assets/Prefabs/UI/MatterIcon.prefab.meta
  Assets/Prefabs/UI/ObjectInfoCanvas.prefab
  Assets/Scenes/Level2.unity
  Assets/Scenes/Level3.unity
  Assets/Scripts/ContentsUI.cs
  Assets/Scripts/ContentsUI.cs.meta
  Assets/Scripts/Equipment.cs
  Assets/Scripts/Interactables/ModifiableObject.cs
  Assets/Scripts/Interactor.cs
  Assets/Scripts/MatterIcon.cs
  Assets/Scripts/MatterIcon.cs.meta
  Assets/Shaders/UI/UIBillboard.shader
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  Assets/Textures/smoke.png.meta
Labels: UI, feature, gameplay

#124 Serialize equipment contents to synchronize them with connecting clients
  Assets/Scripts/Equipment.cs
Labels: bug

#125 Register matter object prefabs dynamically
  Assets/Prefabs/NetworkManager.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scripts/ScriptableObjects/Matter/Matter.cs
  Assets/Scripts/TestNetworkManager.cs
Labels: improvement, networking

#126 Demand Queue memory leak
  Assets/Prefabs/UI/DemandedMatterUI.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scripts/DemandedMatterUI.cs
Labels: UI, bug

#130 fixed wrong input and output
  Assets/Prefabs/Level/AceticAcidEquip.prefab
  Assets/Scenes/Level3.unity
Labels: bug, level

#132 Fix leftover input elements
  Assets/Scripts/Equipment.cs
Labels: UI, bug, gameplay

#134 Serialize the held object for interactors
  Assets/Scripts/Interactor.cs
Labels: bug, networking

#127 Proper Level UI reset & UI anchors + scaling
  Assets/Prefabs/UI/LevelFinishedUI.prefab
  Assets/Prefabs/UI/LevelUI.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Level.Finished.cs
  Assets/Scripts/Level.Init.cs
  Assets/Scripts/Level.Playing.cs
  Assets/Scripts/LevelFinishedUI.cs
  Assets/Scripts/UIManager.cs
Labels: UI, bug

#137 Models for supply boxes & trash cans
  Assets/Materials/MatterSupplyBoxDisplay.mat
  Assets/Models/LabFurnishing/SupplyBox.fbx
  Assets/Models/LabFurnishing/SupplyBox.fbx.meta
  Assets/Models/LabFurnishing/TrashCan.fbx
  Assets/Models/LabFurnishing/TrashCan.fbx.meta
  Assets/Models/LabFurnishing/_LabFurnishing.blend
  Assets/Models/LabFurnishing/_LabFurnishing.blend1
  Assets/Prefabs/Level/MatterSupplyBox.prefab
  Assets/Prefabs/Level/TrashCan.prefab
  Assets/Scenes/Level1.unity
  Assets/Scripts/MatterSupplyBox.cs
Labels: 3D art, assets

#135 Implemented Tutorial
  Assets/GameData/Recipes/Multitool/RecipeWaterTutorial.asset
  Assets/GameData/Recipes/Multitool/RecipeWaterTutorial.asset.meta
  Assets/Prefabs/UI/TutorialUI.prefab
  Assets/Prefabs/UI/TutorialUI.prefab.meta
  Assets/Prefabs/UI/UIManager.prefab
  Assets/Prefabs/UI/lvlStartMessage.prefab
  Assets/Prefabs/UI/lvlStartMessage.prefab.meta
  Assets/Scenes/Level0.unity
  Assets/Scenes/Level1.unity
  Assets/Scenes/Level2.unity
  Assets/Scenes/Level3.unity
  Assets/Scenes/MainScene.unity
  Assets/Scripts/CloseLvlStartMessage.cs
  Assets/Scripts/CloseLvlStartMessage.cs.meta
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Level.cs
  Assets/Scripts/TutorialUI.cs
  Assets/Scripts/TutorialUI.cs.meta
  Assets/Scripts/UIManager.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  Assets/Textures/Sprites/Materials/h2o.mat
  Assets/Textures/Sprites/UI.meta
  Assets/Textures/Sprites/UI/arrow.png
  Assets/Textures/Sprites/UI/arrow.png.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: gameplay, level, sprint

#143 replaced tank in methanolEquip
  Assets/Prefabs/Level/MethanolEquipmentSmall.prefab
  Assets/Prefabs/Level/MethanolEquipmentSmall.prefab.meta
  Assets/Scenes/Level2.unity
Labels: assets

#144 fixed orb height when taking them out of a supply box
  Assets/Scenes/Level0.unity
  Assets/Scenes/Level1.unity
  Assets/Scenes/Level2.unity
  Assets/Scenes/Level3.unity
Labels: gameplay

#147 Fix equip deserialization
  Assets/Scripts/Equipment.cs
  Assets/Scripts/Interactor.cs
Labels: bug

#150 Did some balancing for points/timers/penalties
  Assets/GameData/Matter/Compounds/CompoundC2H4O2.asset
  Assets/GameData/Matter/Compounds/CompoundC2H6.asset
  Assets/GameData/Matter/Compounds/CompoundC2H6O.asset
  Assets/GameData/Matter/Compounds/CompoundC5H4N4O3.asset
  Assets/GameData/Matter/Compounds/CompoundCH4.asset
  Assets/GameData/Matter/Compounds/CompoundCH4O.asset
  Assets/GameData/Matter/Compounds/CompoundCO.asset
  Assets/GameData/Matter/Compounds/CompoundCO2.asset
  Assets/GameData/Matter/Compounds/CompoundH2O.asset
  Assets/GameData/Matter/Elements/ElementN.asset
  Assets/GameData/Matter/Elements/ElementO.asset
  Assets/GameData/Matter/Molecules/MoleculeH2.asset
  Assets/GameData/Matter/Molecules/MoleculeO2.asset
  Assets/Scenes/Level2.unity
  Assets/Scenes/Level3.unity
Labels: UI, gameplay, improvement, level

#151 Move progress bar for bunsen burner
  Assets/Prefabs/Level/BunsenBurner.prefab
Labels: UI

#155 updated meta data
  ProjectSettings/ProjectSettings.asset
Labels: meta

#154 Framework integration
  Assets/Prefabs/FrameworkAPI.prefab
  Assets/Prefabs/FrameworkAPI.prefab.meta
  Assets/Prefabs/NetworkManager.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scenes/ServerLoadingScene.unity
  Assets/Scenes/ServerLoadingScene.unity.meta
  Assets/Scripts/Framework.meta
  Assets/Scripts/Framework/FrameworkAPI.cs
  Assets/Scripts/Framework/FrameworkAPI.cs.meta
  Assets/Scripts/Framework/SimpleJSON.cs
  Assets/Scripts/Framework/SimpleJSON.cs.meta
  Assets/Scripts/GameManager.cs
Labels: game framework, sprint

#157 tutorial now working again
  Assets/Scenes/Level0.unity
  Assets/Scenes/Level2.unity
Labels: bug, level

#158 Update Unity to version 2020.1.3f1
  .gitignore
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/VersionControlSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: sprint

#166 Fix matter icon labels not displaying in front of their matter icon
  Assets/Prefabs/UI/MatterIcon.prefab
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
Labels: UI

#167 Add author comment to code files
  Assets/Scripts/CloseLvlStartMessage.cs
  Assets/Scripts/ContentsUI.cs
  Assets/Scripts/Demand.cs
  Assets/Scripts/DemandQueue.cs
  Assets/Scripts/DemandQueueUI.cs
  Assets/Scripts/DemandedMatterUI.cs
  Assets/Scripts/Equipment.cs
  Assets/Scripts/Framework/FrameworkAPI.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Interactables/DrawersTable.cs
  Assets/Scripts/Interactables/IInteractable.cs
  Assets/Scripts/Interactables/ModifiableObject.cs
  Assets/Scripts/Interactables/PickableObject.cs
  Assets/Scripts/Interactor.cs
  Assets/Scripts/Level.Finished.cs
  Assets/Scripts/Level.Init.cs
  Assets/Scripts/Level.Playing.cs
  Assets/Scripts/Level.Preparing.cs
  Assets/Scripts/Level.cs
  Assets/Scripts/LevelFinishedUI.cs
  Assets/Scripts/LevelPhase.cs
  Assets/Scripts/LevelTimer.cs
  Assets/Scripts/LevelTimerUI.cs
  Assets/Scripts/LevelUI.cs
  Assets/Scripts/MatterIcon.cs
  Assets/Scripts/MatterObject.cs
  Assets/Scripts/MatterSupplyBox.cs
  Assets/Scripts/Messages/ConnectionRequestMessage.cs
  Assets/Scripts/Messages/ServerStateMessage.cs
  Assets/Scripts/ObjectHighlighting.cs
  Assets/Scripts/OutputArea.cs
  Assets/Scripts/Player.cs
  Assets/Scripts/PlayerConnection.cs
  Assets/Scripts/PlayerControls.cs
  Assets/Scripts/PlayerInfo.cs
  Assets/Scripts/RemoveObjectSingleplayer.cs
  Assets/Scripts/RemoveObjectSingleplayer.cs.meta
  Assets/Scripts/ResetZone.cs
  Assets/Scripts/ScoreDisplay.cs
  Assets/Scripts/ScriptableObjects/Matter/Matter.cs
  Assets/Scripts/ScriptableObjects/Matter/MatterCompound.cs
  Assets/Scripts/ScriptableObjects/Matter/MatterElement.cs
  Assets/Scripts/ScriptableObjects/Matter/MatterMolecule.cs
  Assets/Scripts/ScriptableObjects/Recipes/Recipe.cs
  Assets/Scripts/ScriptableObjects/Recipes/RecipeMatchState.cs
  Assets/Scripts/State.cs
  Assets/Scripts/StateMachine.cs
  Assets/Scripts/TestNetworkManager.cs
  Assets/Scripts/TutorialUI.cs
  Assets/Scripts/UIBillboard.cs
  Assets/Scripts/UIManager.cs
  Assets/Scripts/Utils.cs
Labels: documentation

#169 added documentation
  Assets/Scripts/CloseLvlStartMessage.cs
Labels: documentation

#170 updated readme
  README.md
Labels: documentation

#171 adds player party ui
  Assets/Prefabs/UI/PlayerPartyUI.prefab
  Assets/Prefabs/UI/PlayerPartyUI.prefab.meta
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Level.Finished.cs
  Assets/Scripts/Level.Preparing.cs
  Assets/Scripts/PlayerParty.cs
  Assets/Scripts/PlayerParty.cs.meta
  Assets/Scripts/UIManager.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
Labels: UI, feature

#172 Preparing Timer UI and animations
  Assets/Animations/UI.meta
  Assets/Animations/UI/PreparingUI.meta
  Assets/Animations/UI/PreparingUI/_PreparingUI.controller
  Assets/Animations/UI/PreparingUI/_PreparingUI.controller.meta
  Assets/Animations/UI/PreparingUI/go.anim
  Assets/Animations/UI/PreparingUI/go.anim.meta
  Assets/Animations/UI/PreparingUI/hidden.anim
  Assets/Animations/UI/PreparingUI/hidden.anim.meta
  Assets/Animations/UI/PreparingUI/pop.anim
  Assets/Animations/UI/PreparingUI/pop.anim.meta
  Assets/Animations/UI/PreparingUI/ready.anim
  Assets/Animations/UI/PreparingUI/ready.anim.meta
  Assets/Prefabs/UI/LevelTimerUI.prefab
  Assets/Prefabs/UI/LevelUI.prefab
  Assets/Prefabs/UI/PreparingUI.prefab
  Assets/Prefabs/UI/PreparingUI.prefab.meta
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Level.Finished.cs
  Assets/Scripts/Level.Init.cs
  Assets/Scripts/Level.Playing.cs
  Assets/Scripts/Level.Preparing.cs
  Assets/Scripts/Level.cs
  Assets/Scripts/LevelUI.cs
  Assets/Scripts/PreparingUI.cs
  Assets/Scripts/PreparingUI.cs.meta
Labels: UI

#174 remove highscore
  Assets/Scenes/MainScene.unity
Labels: UI

#175 Next Level Button at last level is now similar to Exit Button
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/UI/LevelFinishedUI.prefab
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Level.Finished.cs
  Assets/Scripts/LevelFinishedUI.cs
Labels: UI, game framework

#178 176 polishing
  Assets/Materials/FloorLvl1.mat
  Assets/Materials/FloorLvl1.mat.meta
  Assets/Materials/New Material.mat
  Assets/Scenes/Level3.unity
Labels: improvement

#179 Increase server tick rate
  Assets/Prefabs/NetworkManager.prefab
Labels: bug, gameplay, networking

#180 Fix displaying a zero on the preparing UI
  Assets/Scripts/Level.Preparing.cs
Labels: improvement
