Repository thm-mni-ii/SWT-P_SS20_Overcooked, pull requests merged in 2020-07, with the labels that each got.

#46 Finished objects output
  Assets/Prefabs/Level/Output.prefab
  Assets/Prefabs/NetworkManager.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Interactables/PickableObject.cs
  Assets/Scripts/OutputArea.cs
  Assets/Scripts/OutputArea.cs.meta
Labels: gameplay, sprint

#47 Synchronize device output with clients
  Assets/Scripts/Equipment.cs
Labels: bug, gameplay, networking

#49 Fix multitool client-side insertion bug
  Assets/Scenes/Level1.unity
  Assets/Scripts/Equipment.cs
Labels: bug, networking

#54 Improve player movement
  Assets/Physics.meta
  Assets/Physics/PlayerPM.physicMaterial
  Assets/Physics/PlayerPM.physicMaterial.meta
  Assets/Prefabs/Player.prefab
  Assets/Scripts/PlayerControls.cs
Labels: gameplay

#60 Fix a client-side warning
  Assets/Scripts/Timer.cs
Labels: bug

#62 Add recipes for CO and CO2 + Increase time between demands
  Assets/GameData/Recipes/RecipeCarbonDioxide.asset
  Assets/GameData/Recipes/RecipeCarbonDioxide.asset.meta
  Assets/GameData/Recipes/RecipeCarbonMonoxide.asset
  Assets/GameData/Recipes/RecipeCarbonMonoxide.asset.meta
  Assets/Prefabs/Level/NaCl_Experiment_Equipment.prefab
  Assets/Scenes/Level1.unity
  Assets/Scripts/Level.cs
Labels: assets, feature, gameplay

#64 Fix multitool softlock
  Assets/Prefabs/Level/NaCl_Experiment_Equipment.prefab
  Assets/Scripts/Equipment.cs
  Assets/Scripts/ScriptableObjects/Recipes/Recipe.cs
Labels: bug, gameplay

#65 Implement supply boxes and trash cans
  Assets/Materials/ElementSupplyBoxDisplay.mat
  Assets/Materials/ElementSupplyBoxDisplay.mat.meta
  Assets/Materials/MultitexturedCube.mat
  Assets/Materials/MultitexturedCube.mat.meta
  Assets/Prefabs/Level/ElementSupplyBox.prefab
  Assets/Prefabs/Level/ElementSupplyBox.prefab.meta
  Assets/Prefabs/Level/TrashCan.prefab
  Assets/Prefabs/Level/TrashCan.prefab.meta
  Assets/Scenes/Level1.unity
  Assets/Scripts/ElementSupplyBox.cs
  Assets/Scripts/ElementSupplyBox.cs.meta
  Assets/Shaders/MultitexturedCube.shader
  Assets/Shaders/MultitexturedCube.shader.meta
Labels: feature, gameplay

#68 Rework game timer, synchronize it without using SyncVar
  Assets/Scripts/GameTimer.cs
  Assets/Scripts/Level.cs
Labels: improvement, networking

#70 Remove decimals & improve game timer display
  Assets/Scripts/GameTimer.cs
Labels: UI, improvement

#71 Revert "Remove decimals & improve game timer display"
  Assets/Scripts/GameTimer.cs
Labels: meta

#72 Fix game timer and syncvar merge
  Assets/Scripts/GameTimer.cs
Labels: meta

#73 Design level finished screen
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/UI/LevelFinishedUI.prefab
  Assets/Prefabs/UI/LevelFinishedUI.prefab.meta
  Assets/Prefabs/UI/UIManager.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/LevelFinishedUI.cs
  Assets/Scripts/LevelFinishedUI.cs.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  Assets/Textures/Sprites/Star.png
  Assets/Textures/Sprites/Star.png.meta
  Assets/Textures/Sprites/StarEmpty.png
  Assets/Textures/Sprites/StarEmpty.png.meta
Labels: 2D art, UI, assets, feature, sprint

#80 Disable collisions for picked up objects
  Assets/Materials/MatterSupplyBoxDisplay.mat
  Assets/Materials/MatterSupplyBoxDisplay.mat.meta
  Assets/Prefabs/Level/MatterSupplyBox.prefab
  Assets/Prefabs/Level/MatterSupplyBox.prefab.meta
  Assets/Prefabs/Level/NaCl_Experiment_Equipment.prefab
  Assets/Prefabs/MatterObjects/Compounds/CarbonDioxide.prefab
  Assets/Prefabs/MatterObjects/Compounds/CarbonMonoxide.prefab
  Assets/Prefabs/MatterObjects/Compounds/Water.prefab
  Assets/Prefabs/MatterObjects/Elements/Carbon.prefab
  Assets/Prefabs/MatterObjects/Elements/Hydrogen.prefab
  Assets/Prefabs/MatterObjects/Elements/Oxygen.prefab
  Assets/Prefabs/MatterObjects/MatterObject.prefab
  Assets/Prefabs/MatterObjects/MatterObject.prefab.meta
  Assets/Prefabs/MatterObjects/Molecules/DiHydrogen.prefab
  Assets/Prefabs/MatterObjects/Molecules/DiOxide.prefab
  Assets/Scripts/ElementObject.cs
  Assets/Scripts/ElementSupplyBox.cs
  Assets/Scripts/Equipment.cs
  Assets/Scripts/Interactables/PickableObject.cs
  Assets/Scripts/Level.cs
  Assets/Scripts/MatterObject.cs
  Assets/Scripts/MatterObject.cs.meta
  Assets/Scripts/MatterSupplyBox.cs
  Assets/Scripts/MatterSupplyBox.cs.meta
  Assets/Scripts/OutputArea.cs
  Assets/Scripts/ScriptableObjects/Matter/Matter.cs
Labels: bug, gameplay, improvement
